campus = {
    'utm': 'Mississauga',
    'utsc': 'Scarborough',
    'utsg': 'St. George'
}

division = {
    'apsc': 'Faculty of Applied Science & Engineering',
    'artsci': 'Faculty of Arts and Science',
    'music': 'Faculty of Music',
    'arcla': 'John H. Daniels Faculty of Architecture, Landscape, & Design',
    'utm':' University of Toronto Mississauga', 
    'utsc': 'University of Toronto Scarborough' 
}

department = {
    'asdn':'ASDN: Arts and Science: Office of the Dean',
    'ana':'Anatomy and Cell Biology',
    'ant':'Anthropology',
    'antsc':'Anthropology (UTSC)',
    'fah':'Art History',
    'ast':'Astronomy and Astrophysics',
    'bsh': 'Biochemistry',
    'biosc':'Biological Sciences (UTSC)',
    'umbio':'Biology',
    'cita':'Canadian Institute for Theoretical Astrophysics',
    'csb':'Cell and Systems Biology',
    'crim':'Centre for Criminology and Sociolegal Studies',
    'cdssc':'Centre for Critical Development Studies (UTSC)',
    'dts':'Centre for Diaspora & Transnational Studies',
    'drama':'Centre for Drama: Theatre and Performance Studies',
    'ceres':'Centre for European: Russian and Eurasian Studies',
    'ire':'Centre for Industrial Relations and Human Resources',
    'csus':'Centre for Study of United States',
    'ctlsc':'Centre for Teaching and Learning (UTSC)',
    'che':'Chemical Engineering and Applied Chemistry',
    'chmps':'Chemical and Physical Sciences',
    'chm':'Chemistry',
    'cine':'Cinema Studies Institute',
    'civil':'Civil and Mineral Engineering',
    'clas':'Classics',
    'csc':'Computer Science',
    'cdp':'Cross Disciplinary Programs Office',
    'rlg':'Department for the Study of Religion',
    'acmsc':'Dept. of Arts: Culture & Media (UTSC)',
    'cmssc':'Dept. of Computer & Mathematical Sci (UTSC)',
    'hcssc':'Dept. of Historical & Cultural Studies (UTSC)',
    'pessc':'Dept. of Physical & Environmental Sci (UTSC)',
    'esc':'Division of Engineering Science',
    'es':'Earth Sciences',
    'eas':'East Asian Studies',
    'eeb':'Ecology and Evolutionary Biology',
    'eco':'Economics',
    'ece':'Edward S. Rogers Sr. Dept. of Electrical & Computer Engin.',
    'ae1':'Engineering First Year Office',
    'eng':'English',
    'engsc':'English (UTSC)',
    'engdr':'English and Drama',
    'fifsw':'Factor Inwentash Faculty of Social Work', 
    'apsc':'Faculty of Applied Science & Engineering',
    'artsci':'Faculty of Arts and Science',
    'music':'Faculty of Music',
    'fre':'French',
    'ggr':'Geography and Planning',
    'umggr':'Geography: Geomatics and Environment',
    'ger':'Germanic Languages & Literatures',
    'chssc':'Health and Society (UTSC)',
    'hiscl':'Historical Studies',
    'his':'History',
    'hmb':'Human Biology Program',
    'ggrsc':'Human Geography (UTSC)',
    'imm':'Immunology',
    'asabs':'Indigenous Studies Arts & Science',
    'istep':'Inst for Studies in Transdisciplinary Engin Educ & Practice',
    'ihpst':'Inst. for the History & Philosophy of Science & Technology',
    'imi':'Institute for Management and Innovation',
    'isup':'Institute for the Study of University Pedagogy',
    'bme':'Institute of Biomedical Engineering',
    'icc':'Institute of Communication and Culture',
    'ita':'Italian Studies',
    'jsp':'Jewish Studies',
    'arcla':'John H. Daniels Faculty of Architecture: Landscape: & Design',
    'lmp':'Laboratory Medicine and Pathobiology',
    'fgi':'Language Studies',
    'cflsc':'Language Studies (UTSC)',
    'lin':'Linguistics',
    'ummgt':'Management',
    'mgtsc':'Management (UTSC)',
    'mms':'Materials Science and Engineering',
    'mcs':'Mathematical and Computational Sciences',
    'mat':'Mathematics',
    'mie':'Mechanical & Industrial Engineering',
    'medgm':'Molecular Genetics',
    'glaf':'Munk School of Global Affairs and Public Policy',
    'nmc':'Near & Middle Eastern Civilizations',
    'new':'New College',
    'nusci':'Nutritional Sciences',
    'pcl':'Pharmacology',
    'phl':'Philosophy',
    'phlsc':'Philosophy (UTSC)',
    'phy':'Physics',
    'psl':'Physiology',
    'pol':'Political Science',
    'polsc':'Political Science (UTSC)',
    'psy':'Psychology',
    'psysc':'Psychology (UTSC)',
    'compg':'Rotman Commerce',
    'envmt':'School of Environment',
    'sdst':'Sexual Diversity Studies',
    'sla':'Slavic Languages and Literatures',
    'soc':'Sociology',
    'socsc':'Sociology (UTSC)',
    'spa':'Spanish and Portuguese',
    'smc':'St. Michael\'s College',
    'stat':'Statistical Sciences',
    'trin':'Trinity College',
    'uc':'University College',
    'utm':'University of Toronto Mississauga',
    'utsc':'University of Toronto Scarborough',
    'vic':'Victoria College',
    'umvis':'Visual Studies',
    'wgsi':'Women and Gender Studies Institute'
}

utsc_breadth = {
    'alnl': 'Arts, Literature & Language', 
    'hpcs': 'History, Philosophy & Cultural Studies',
    'ns': 'Natural Sciences', 
    'qr': 'Quantitative Reasoning',
    'sbs': 'Social & Behavioural Sciences' 
}

apsc_electives = {
    'ans': 'APSc-Natural Science',
    'cs': 'Complementary Studies',
    'cshss': 'Complementary Studies or Humanities & Social Sciences'
}

utm_distribution = {
    'hum': 'Humanities', 
    'sci': 'Science',
    'scihum': 'Science or Humanities',
    'ss': 'Social Science',
    'sshum': 'Social Science or Humanities'
}

arts_and_science_breadth = {
    '1': '(1) Creative and Cultural Representation',
    '13': '(1) Creative and Cultural Representation + (3) Society and its Institutions', 
    '2': '(2) Thought, Belief and Behaviour',
    '3': '(3) Society and its Institutions', 
    '32': '(3) Society and its Institutions + (2) Thought, Belief and Behaviour',
    '4': '(4) Living Things and Their Environment',
    '43': '(4) Living Things and Their Environment + (3) Society and its Institutions',
    '5': '(5) The Physical and Mathematical Universes',
    '53': '(5) The Physical and Mathematical Universes + (3) Society and its Institutions'
}

arts_and_science_distribution = {
    'hum': 'Humanities',
    'humsci': 'Humanities or Science',
    'humss': 'Humanities or Social Science',
    'sci': 'Science',
    'sciss': 'Science or Social Science',
    'ss': 'Social Science'
}
